"""initial migration

Revision ID: 48e0643fa971
Revises:
Create Date: 2024-01-31 21:52:29.836125

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '48e0643fa971'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Common name of provider e.g Safaricom or Standard Chartered'),
    sa.Column('organization_type', sa.Enum('BANK', 'TELCO', 'OTHER', name='orgtype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_type')
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=20)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False, comment='ISO 4217 Currency Code'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbols', sa.ARRAY(sa.String(length=10)), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('individual_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('social_links', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False, comment='How long does a subscription last'),
    sa.Column('name', sa.String(), nullable=False, comment='For example basic, pro, enterprise'),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email used to register.'),
    sa.Column('phone_number', sa.String(length=30), nullable=True, comment='Email used to contact user or to send alerts to.'),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DECIMAL(), nullable=False),
    sa.Column('updated_at', sa.DECIMAL(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=False, comment='Whether or not user has signed up'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='Any extra information we may want to keep as JSON'),
    sa.Column('uuid', sa.Uuid(), nullable=False, comment='Less guessable id to use in application'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('transactional_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=500), nullable=False, comment='Name associated with this account for example Facebook .inc or John Smith.'),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('holder_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.DECIMAL(), nullable=True, comment='Balance of account at last_checked'),
    sa.Column('last_checked', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['holder_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['account_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False, comment='Type of the account e.g Hifadhi Current Account'),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('identifier', 'account_type')
    )
    op.create_table('mobile_money_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('maybe_number', sa.String(length=30), nullable=False, comment='May be obfuscated. Use phone_number for usable number'),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('provider_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('safaricom_buygoods_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('buygoods_number', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('buygoods_number')
    )
    op.create_table('safaricom_paybill_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('paybill_number', sa.String(length=10), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True, comment='May not always be present since sometimes organizations use them to partition accounts'),
    sa.ForeignKeyConstraint(['account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('paybill_number'),
    sa.UniqueConstraint('paybill_number', 'account_number')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('initiated_at', sa.DECIMAL(), nullable=False, comment='When did this transaction happen'),
    sa.Column('owner_account_id', sa.Integer(), nullable=False),
    sa.Column('participant_account_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=50), nullable=True, comment='Reference given along with transaction'),
    sa.Column('original_detail', sa.String(length=500), nullable=True, comment='Original text that was part of transaction message.'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='Any extra information we may want to keep as JSON'),
    sa.ForeignKeyConstraint(['owner_account_id'], ['transactional_account.id'], ),
    sa.ForeignKeyConstraint(['participant_account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount', 'initiated_at', 'owner_account_id', 'participant_account_id')
    )
    op.create_table('web_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DECIMAL(), nullable=False),
    sa.Column('expires_after', sa.Interval(), nullable=False, comment='How long a web report should stay live'),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('web_url', sa.String(length=150), nullable=False, comment='URL for web report'),
    sa.Column('last_visit', sa.DECIMAL(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['transactional_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_report')
    op.drop_table('transaction')
    op.drop_table('safaricom_paybill_account')
    op.drop_table('safaricom_buygoods_account')
    op.drop_table('provider_account')
    op.drop_table('mobile_money_account')
    op.drop_table('bank_account')
    op.drop_table('transactional_account')
    op.drop_table('user_account')
    op.drop_table('subscription_plan')
    op.drop_table('individual_profile')
    op.drop_table('currency')
    op.drop_table('company_profile')
    op.drop_table('account_provider')
    # ### end Alembic commands ###
