"""create contact request table

Revision ID: e7a3b53426f3
Revises: 6e6e9fc78065
Create Date: 2024-02-13 16:25:24.936976

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7a3b53426f3'
down_revision: Union[str, None] = '6e6e9fc78065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DECIMAL(), nullable=False),
    sa.Column('isAddressed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_request')
    # ### end Alembic commands ###
