[default]
LOG_LEVEL = "DEBUG"

CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULTS_BACKEND = "redis://localhost:6379"

MAIL_USER = "dev@pesarifu.com"
APP_BASE_URL = "https://app.pesarifu.com/"

STATEMENTS_BASE_DIR = "@format {env[APP_ROOT]}/uploads"
EXPORTS_BASE_DIR = "@format {env[APP_ROOT]}/exports"
