[default]
LOG_LEVEL = "DEBUG"

CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULTS_BACKEND = "redis://localhost:6379"

MAIL_USER = "dev@pesarifu.com"

STATEMENTS_BASE_DIR = "@format {env[APP_ROOT]}/uploads"
EXPORTS_BASE_DIR = "@format {env[APP_ROOT]}/exports"

[development]
APP_BASE_URL = "http://localhost:3005/"
REPORTS_BASE_URL = "http://localhost:3010/"
WEBSITE_BASE_URL = "http://localhost:3000/"


[production]
APP_BASE_URL = "https://app.pesarifu.com/"
REPORTS_BASE_URL = "https://reports.pesarifu.com/"
WEBSITE_BASE_URL = "https://pesarifu.com/"
